### ISSUE TITLE
Found secret keys

### ISSUE THREAD

**Issue by pawanrawat07** [EliteDevSolution/Bandwidth-Api-Integration#1]
Hii 
I'm a security researcher. I found some sensitive keys in your github repo. Plz take a look on it
https://github.com/EliteDevSolution/Bandwidth-Api-Integration/blob/d5231d1b2de6f3ffb7bf6b23fcea72e4400ce622/application/libraries/guzzle.php#L7

If an attacker see these key he takes the advantage of these keys and harm your organization

**Comment by EliteDevSolution** [comment]
Fix done. Thanks.
